Apply redux recompose
Wolox/github-organization-manager-react pull request #7
Opened 2019-09-27 15:29 UTC by betoobernal

## Summary

* adapt screen components to redux-recompose
* adapt reducers to redux-recompose
* adapt actions to redux-recompose

## Screenshots

[Change!] Show the screenshots of the views you modified.

## Trello Card

https://trello.com/c/u9l58025/10-implementar-redux-recompose-en-los-reducers

2019-09-27 17:26 UTC, betoobernal commented on src/redux/Team/actions.js
> +      throw new SubmissionError({ _error: 'Error...' });
Venga, que esto lo puse para cargar el error de la petición al form. Pero aún no pongo el error que es porque no sé si va lo que devuelve el back o simplemente decir que no se pudo realizar la acción.
psd: Perdón por el español.

2019-10-04 12:18 UTC, FrankIglesias requested changes

2019-10-04 12:18 UTC, FrankIglesias commented on src/app/screens/AddMemberToTeam/index.js
> +    return dispatch(teamActions.addMembersToTeam({ ...values, techs }));
check how to refactor this function later

2019-10-04 12:18 UTC, FrankIglesias commented on src/app/screens/AddOwner/layout.js
> +              <option />
add an empty text to the default option

2019-10-04 12:18 UTC, FrankIglesias commented on src/redux/Repository/actions.js
> +      throw new SubmissionError({ _error: 'Error...' });
use i18n later

2019-10-04 12:18 UTC, FrankIglesias commented on src/redux/Repository/actions.js
> +      throw new SubmissionError({ _error: 'Error...' });
same

2019-10-04 12:18 UTC, FrankIglesias commented on src/redux/Repository/actions.js
> +      throw new SubmissionError({ _error: 'Error...' });
same

2019-10-04 12:18 UTC, FrankIglesias commented on src/redux/Repository/actions.js
> +    withPostFailure(dispatch => {
add some kind of descriptive error

2019-10-04 12:18 UTC, FrankIglesias commented on src/redux/Team/actions.js
> +      throw new SubmissionError({ _error: 'Error...' });
same

2019-10-04 12:18 UTC, FrankIglesias commented on src/redux/Team/actions.js
> +      throw new SubmissionError({ _error: 'Error...' });
- Return a more descriptive error like `Hubo un error en la creación del team`

2019-10-04 12:18 UTC, FrankIglesias commented on src/services/RepositoryService.js
> +/* export const createRepository = values => api.post('/repositories', values);
delete commented lines if you are not using it

2019-10-04 12:18 UTC, FrankIglesias commented on src/services/RepositoryService.js
> +export const addMemberToOrg = values =>
if you are going to mock de api, change the whole base url instead of changin for each function

2019-10-04 12:18 UTC, FrankIglesias commented on src/services/RepositoryService.js
> +export const addMemberToOrg = values =>
Move base URL to .env file

2019-10-04 12:18 UTC, FrankIglesias commented on src/services/TeamServices.js
> +export const createTeam = values =>
same

2019-10-04 12:18 UTC, FrankIglesias commented on src/services/TeamServices.js
> +export const getTeams = () => api.get('/teams/');
extra slash at the end

2019-10-07 16:40 UTC, FrankIglesias approved these changes

2019-10-07 16:40 UTC, FrankIglesias commented on src/app/components/AlertInfo/index.js
> +  message: '¡El registro se ha guardado con exito!'
i18n

2019-10-07 16:40 UTC, FrankIglesias commented on src/app/screens/AddOwner/layout.js
> +            <span className="input-group-text">
why this span? why not append classes to the i tag

2019-10-07 16:40 UTC, FrankIglesias commented on src/app/screens/Teams/layout.js
> +          {teamCreated && !loading && <AlertInfo message="¡El equipo se creó con éxito!" />}
i18n

2019-10-07 17:04 UTC, merged